### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by pdiio** [ng-matero/ng-matero#30]
I tried to create a route page in Angular 9:

$ ng g ng-matero:module abc
$ ng g ng-matero:page def -m=abc

I have following exception when executes the first command:

[error] Error: Could not find module "ng-matero" from "C:\\Users\\Paolo\\Documents\\Projects\\badgeMeAngular\\matero9".
    at Object.resolve (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular-devkit\core\node\resolve.js:154:11)
    at NodeModulesEngineHost._resolvePackageJson (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular-devkit\schematics\src\engine\engine.js:147:40)
    at SchematicEngine.createCollection (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular-devkit\schematics\src\engine\engine.js:140:43)
    at GenerateCommand.getCollection (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular\cli\models\schematic-command.js:128:35)
    at GenerateCommand.initialize (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular\cli\models\schematic-command.js:44:37)
    at async GenerateCommand.initialize (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular\cli\commands\generate-impl.js:12:9)
    at async GenerateCommand.validateAndRun (C:\Users\Paolo\Documents\Projects\badgeMeAngular\matero9\node_modules\@angular\cli\models\command.js:124:9)

**Comment by nzbin** [comment]
Maybe you not installed  `ng-matero` correctly. Now v9 has released!
