### ISSUE TITLE
MergeConflictException when adding ng-matero to NX workspace

### ISSUE THREAD

**Issue by gs-scooter** [ng-matero/ng-matero#351]
I have an NX workspace with an Angular application and would like to add ng-matero to it. I initially installed the package via `npm i` and then tried running the `ng-add` generator with this command: `nx g ng-matero:ng-add`. 

Following is the output:

```
√ Choose a prebuilt layout template: · static
√ Choose a prebuilt navigation type: · side
√ Choose a prebuilt theme style: · light  
√ Choose a prebuilt direction option: · ltr
√ Set up browser animations for Angular Material? (Y/n) · true
✔ Packages installed successfully.
MergeConflictException [Error]: A merge conflicted on path "/.eslintrc.json".
    at C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:141:35
    at Array.forEach (<anonymous>)
    at HostTree.merge (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:130:23)
    at MapSubscriber.project (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\src\rules\base.js:54:103)
    at MapSubscriber._next (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TapSubscriber._next (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\Developer\dev\data-library-platform\data-library-workspace\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
A merge conflicted on path "/.eslintrc.json".
```

Any ideas on how to proceed?

**Comment by nzbin** [comment]
I'm sorry ng-matero don't support the NX workspace yet. I will add a NX starter example.

**Comment by DavidSandor** [comment]
Hi, same problem here. Any update on when its going to be usable? Or workaround maybe? Thanks

**Comment by nzbin** [comment]
@gs-scooter @DavidSandor 
I created a nx starter, you can have a try. https://github.com/ng-matero/nx-starter

**Comment by DavidSandor** [comment]
Hey, it would be nice thanks, but for me when I run 'npm start ng-matero' it generates browser application bundles forever and the application does not start. Any ideas?

**Comment by Wurmloch** [comment]
Got it to run with an updated `package.json`, copied it over from the dependencies in the main repo:
```json
{
  "name": "nx-starter",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.3.6",
    "@angular/cdk": "~13.3.6",
    "@angular/common": "~13.3.6",
    "@angular/compiler": "~13.3.6",
    "@angular/core": "~13.3.6",
    "@angular/flex-layout": "^13.0.0-beta.38",
    "@angular/forms": "~13.3.6",
    "@angular/localize": "~13.3.6",
    "@angular/material": "~13.3.6",
    "@angular/material-moment-adapter": "~13.3.6",
    "@angular/platform-browser": "~13.3.6",
    "@angular/platform-browser-dynamic": "~13.3.6",
    "@angular/router": "~13.3.6",
    "@ng-matero/extensions": "^13.2.0",
    "@ng-matero/extensions-moment-adapter": "^13.0.0",
    "@ngx-formly/core": "^5.12.0",
    "@ngx-formly/material": "^5.12.0",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "angular-in-memory-web-api": "~0.13.0",
    "apexcharts": "^3.35.0",
    "moment": "^2.29.3",
    "moment-timezone": "^0.5.34",
    "ngx-permissions": "^13.0.1",
    "ngx-progressbar": "^8.0.0",
    "ngx-toastr": "^14.3.0",
    "photoviewer": "^3.6.2",
    "rxjs": "~7.5.5",
    "screenfull": "^6.0.1",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.6",
    "@angular-eslint/eslint-plugin": "~13.1.0",
    "@angular-eslint/eslint-plugin-template": "~13.1.0",
    "@angular-eslint/template-parser": "~13.1.0",
    "@angular/cli": "~13.3.6",
    "@angular/compiler-cli": "~13.3.6",
    "@angular/language-service": "~13.3.6",
    "@nrwl/cli": "14.1.4",
    "@nrwl/cypress": "14.1.4",
    "@nrwl/eslint-plugin-nx": "14.1.4",
    "@nrwl/jest": "14.1.4",
    "@nrwl/linter": "14.1.4",
    "@nrwl/workspace": "14.1.4",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "~5.18.0",
    "@typescript-eslint/parser": "~5.18.0",
    "cypress": "^9.1.0",
    "eslint": "~8.12.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.5.1",
    "jest-preset-angular": "11.1.1",
    "nx": "14.1.4",
    "prettier": "^2.5.1",
    "stylelint": "^14.9.0",
    "stylelint-config-rational-order": "^0.1.2",
    "stylelint-config-recommended-scss": "^6.0.0",
    "stylelint-config-standard": "^25.0.0",
    "stylelint-order": "^5.0.0",
    "stylelint-scss": "^4.2.0",
    "ts-jest": "27.1.4",
    "ts-node": "9.1.1",
    "typescript": "~4.6.2"
  }
}

```
