### ISSUE TITLE
执行ng add ng-matero报错

### ISSUE THREAD

**Issue by girvs** [ng-matero/ng-matero#64]
执行ng add ng-matero报错

```
Error: Error on worker #5: Error: No typings declaration can be found for the referenced NgModule class in static withConfig(configOptions,
        // tslint:disable-next-line:max-line-length
        breakpoints = []) {
            return {
                ngModule: FlexLayoutModule,
                providers: configOptions.serverLoaded ?
                    [
                        { provide: LAYOUT_CONFIG, useValue: Object.assign(Object.assign({}, DEFAULT_CONFIG), configOptions) },
                        { provide: BREAKPOINT, useValue: breakpoints, multi: true },
                        { provide: SERVER_TOKEN, useValue: true },
                    ] : [
                    { provide: LAYOUT_CONFIG, useValue: Object.assign(Object.assign({}, DEFAULT_CONFIG), configOptions) },
                    { provide: BREAKPOINT, useValue: breakpoints, multi: true },
                ]
            };
        }.
    at ModuleWithProvidersAnalyzer.resolveNgModuleReference (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:178:23)
    at ModuleWithProvidersAnalyzer.getDtsModuleWithProvidersFunction (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:165:33)
    at E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:46:43
    at Array.forEach (<anonymous>)
    at E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:39:28
    at Array.forEach (<anonymous>)
    at ModuleWithProvidersAnalyzer.analyzeProgram (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:37:23)
    at Transformer.analyzeProgram (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:132:45)
    at Transformer.transform (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:75:27)
    at E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:48:42
    at ClusterMaster.onWorkerMessage (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:194:27)
    at E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:54:95
    at ClusterMaster.<anonymous> (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:292:57)
    at step (E:\angular\cmmp-manager\node_modules\tslib\tslib.js:141:27)
    at Object.next (E:\angular\cmmp-manager\node_modules\tslib\tslib.js:122:57)
    at E:\angular\cmmp-manager\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (E:\angular\cmmp-manager\node_modules\tslib\tslib.js:111:16)
    at EventEmitter.<anonymous> (E:\angular\cmmp-manager\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:286:32)
    at EventEmitter.emit (events.js:310:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cmmp-manager@0.0.0 postinstall: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cmmp-manager@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-08-18T04_01_11_283Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.
```

**Comment by kenany92** [comment]
Hi @girvs 
which @angular/cli version please are you using?

**Comment by girvs** [comment]
@kenany92  9.1.12

**Comment by kenany92** [comment]
Can you share your package.json file or just tell about the version on ng-matero you are using?

I had the almost same issue. I used ng-matero 10 with angular/cli 8 there was a mismatch between dependencies version. I just removed the project, upgrade angular/cli to 10 then create the new project, now It works  fine.

**Comment by nzbin** [comment]
Ng-Matero must be installed in a new Angular project and should use 9.x.x with Angular v9.

**Comment by AliAUZ** [comment]
Upgrade to the v10
